/**
	Get the size of the call stack.
	int get_call_stack_size();
	## Returns:
		int: the size of the call stack (i.e. how many functions deep are you currently?)
	## Remarks:
		This function doesn't work in the context of exceptions. If you call it in a catch block, you'll most likely get the call stack in the try block, not what actually threw the exception.
*/

// Example:
void test1() {test2();}
void test2() {test3();}
void test3() {test4();}
void test4() {
	alert("Call stack size is", get_call_stack_size());
}

void main() {
	test1();
}
